std = "roblox"

[rules]
if_same_then_else = "allow"
global_usage = "allow"
multiple_statements = "allow"
unused_variable = "allow"
unscoped_variables = "allow"
shadowing = "allow"
incorrect_standard_library_use = "allow"
undefined_variable = "allow"
type_check_inside_call = "allow"
empty_loop = "allow"
parenthese_conditions = "allow"
mixed_table = "allow"