return {
    
    Astra = {
        { Text = "ZmanDem7", Desc = "PBASTPanel Lead Maintainer + PBASTPanel Lead Developer" }
    },
    Adonis = {
        { Text = "Sceleratis/Davey_Bones", Desc = "Made Adonis & EISS" },
        { Text = "Kohltastrophe (Scripth)", Desc = "For his help with various things and some code" },
        {
            Text = "einsteinK",
            Desc = "Helped me with some scripting problems early in development and put together the LoadstringParser; Best programmer I know",
        },
        {
            Text = "Rerumu",
            Desc = "Numerous contributions (Endless stairs, FiOne, Parser, Steampunk theme)",
        },
		{ Text = "Cald_fan", Desc = "Adonis Maintainer + WebPanel Creator" },
		{ Text = "joritochip", Desc = "Adonis Maintainer + WebPanel Developer" },
        { Text = "Coasterteam", Desc = "Adonis Maintainer + Development contributions (Kronos developer)" },
    },
    Misc = {
        { Text = "Stravant/JustAPerson/Jason Priest (?)", Desc = "Author of GoodSignal" },
        { Text = "darkelementallord", Desc = "Updated some guis" },
        {
            Text = "TheFurryFish",
            Desc = "Gave me some dank ideas like local particles and some loading related things; and helped debug",
        },
        { Text = "Moistality", Desc = "Helped with finding and patching vulns" },
        { Text = "GigsD4X/F3X", Desc = "F3X Building Tool" },
        { Text = "Drezmor", Desc = "Resize was originally ripped from his ohgals and modified" },
        { Text = "KingKeith55", Desc = "Provided the Stickify command" },
        { Text = "NickPatella", Desc = "Made the piano used in the !piano command" },
        { Text = "Raspy_Pi", Desc = "Made Dex explorer" },
        { Text = "j1my3p1x", Desc = "His replication checking idea is what lead to the replication logs" },
        { Text = "Bubby4j", Desc = 'Used their "Refresh Icon" image (default theme)' },
        { Text = "meafers", Desc = "Suggested some stuff" },
        { Text = "", Desc = "" },
        { Text = "~ :) ~", Desc = "" },
        { Text = "Donors", Desc = "Donors keep the wheels turning ;)" },
        { Text = "The Users [You :)]", Desc = "For using the script and keeping it alive :)" },
        {
            Text = "Special thanks",
            Desc = "Special thanks to everyone who helped along the way and suggested new ideas!",
        },
        {
            Text = "Not listed?",
            Desc = "Message Davey_Bones and tell me what you need to be credited for and I'll add you in! (also sorry for missing you the first time)",
        },
    },
}
